/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.axelxitumul.vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import org.axelxitumul.modelo.Libro;
import org.axelxitumul.controlador.ControlDelLibro;

/**
 *
 * @author informatica
 */
class PanelDeImagen extends JPanel{
    private Image imagen;   
public PanelDeImagen(Image imagen){
        this.imagen = imagen;
                }
     @Override
     protected void paintComponent(Graphics grafica){
         super.paintComponent(grafica);
         grafica.drawImage(imagen, 0, 0, 400, 300, this);
     }
}

public class VentanaLibreria extends javax.swing.JFrame {

    private Image imagenDelPanel;
    /**
     * Creates new form VentanaLibreria
     */
    public VentanaLibreria() {
        String direccionImagen = "/org/axelxitumul/recursos/Login.jpg";
        cargarImagenDelPanel(this.getClass().getResource(direccionImagen));
        initComponents();
    }
    
    private void cargarImagenDelPanel(URL nombreImagen){
         try{
             imagenDelPanel = ImageIO.read(nombreImagen);
         }catch(IOException error){
             error.printStackTrace();
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelDeImagen(imagenDelPanel);
        lblIdLibro = new javax.swing.JLabel();
        lblAutorLibro = new javax.swing.JLabel();
        lblNombreLibro = new javax.swing.JLabel();
        lblEditorialLibro = new javax.swing.JLabel();
        lblEdicionLibro = new javax.swing.JLabel();
        txtidLibro = new javax.swing.JTextField();
        txtAutorLibro = new javax.swing.JTextField();
        txtNombreLibro = new javax.swing.JTextField();
        txtEdicionLibro = new javax.swing.JTextField();
        btnAgregarLibro = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        txtEditorialLibro = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        lblIdLibro.setBackground(new java.awt.Color(255, 255, 255));
        lblIdLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblIdLibro.setText("ID:");

        lblAutorLibro.setBackground(new java.awt.Color(255, 255, 255));
        lblAutorLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblAutorLibro.setText("Autor");

        lblNombreLibro.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreLibro.setText("Libro");

        lblEditorialLibro.setBackground(new java.awt.Color(255, 255, 255));
        lblEditorialLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblEditorialLibro.setText("Editorial");

        lblEdicionLibro.setBackground(new java.awt.Color(255, 255, 255));
        lblEdicionLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblEdicionLibro.setText("Edicion");

        btnAgregarLibro.setText("Agregar");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");

        btnActualizar.setText("Actualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblIdLibro)
                        .addGap(61, 61, 61)
                        .addComponent(txtidLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutorLibro)
                            .addComponent(lblEdicionLibro)
                            .addComponent(lblEditorialLibro)
                            .addComponent(lblNombreLibro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAutorLibro)
                            .addComponent(txtNombreLibro)
                            .addComponent(txtEdicionLibro)
                            .addComponent(txtEditorialLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregarLibro)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnActualizar))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdLibro)
                    .addComponent(txtidLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorLibro)
                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLibro)
                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditorialLibro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnBorrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdicionLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdicionLibro)))
                    .addComponent(txtEditorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        Libro libro = new Libro();
        libro.setIdLibro(Integer.parseInt(txtidLibro.getText()));
        libro.setNombreDelAutor(txtAutorLibro.getText());
        libro.setNombreDelLibro(txtNombreLibro.getText());
        libro.setNombreDeLaEditorial(txtEditorialLibro.getText());
        libro.setEdicion(Integer.parseInt(txtEdicionLibro.getText()));
        libro.setEstadoLibro(true);
        ControlDelLibro controlador = new ControlDelLibro(); 
        controlador.agregarLibro(libro);
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLibreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutorLibro;
    private javax.swing.JLabel lblEdicionLibro;
    private javax.swing.JLabel lblEditorialLibro;
    private javax.swing.JLabel lblIdLibro;
    private javax.swing.JLabel lblNombreLibro;
    private javax.swing.JTextField txtAutorLibro;
    private javax.swing.JTextField txtEdicionLibro;
    private javax.swing.JTextField txtEditorialLibro;
    private javax.swing.JTextField txtNombreLibro;
    private javax.swing.JTextField txtidLibro;
    // End of variables declaration//GEN-END:variables
}
